apiVersion: apps/v1
kind: Deployment
metadata:
  name: command-server
  namespace: apps
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: command-producer
    spec:
      containers:
      - name: command-app
        image: github.com/ZestOfLife/scalable-live-summarizer-and-transcriber-app/command-server:latest
        env:
          - name: KAFKA_BOOTSTRAP_SERVERS
            value: "command-queue-cluster-kafka-bootstrap.kafka.svc:9092"
          - name: KAFKA_TOPIC_VIDEO
            value: "video-queue"
          - name: KAFKA_TOPIC_AUDIO
            value: "audio-queue"
          - name: KAFKA_TOPIC_SEEK
            value: "seek-queue"
        # Readiness Probe
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: command-service
spec:
  selector:
    app: command-server
  ports:
    - name: grpc
      port: 9090
      targetPort: 9090
