apiVersion: v1
kind: PersistentVolume
metadata:
  name: s3-model-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - region ap-southeast-1
  csi:
    driver: s3.csi.aws.com
    volumeHandle: llm-models-bucket
