syntax = "proto3";
option go_package = "github.com/zestoflife/scalable-live-summarizer-and-transcriber-app";

message MediaStreamRequest {
  oneof payload {
    VideoChunk video = 1;
    AudioChunk audio = 2;
    SeekRequest seek = 3;
  }
}

message VideoChunk {
  string id = 1; // uuid
  bytes data = 2;
  int64 timestamp_start = 3; // in ms
  int64 timestamp_end = 4;   // in ms
}

message AudioChunk {
  string id = 1; // uuid
  bytes data = 2;
  int64 timestamp_start = 3; // in ms
  int64 timestamp_end = 4; // in ms
}

message SeekRequest {
  string id = 1; // uuid
  int64 timestamp_seek = 2; // in ms
}

message Success {
  bool success = 1;
}

service InferenceService {
  rpc ProcessMedia(stream MediaStreamRequest) returns (Success) {}
}
